### ISSUE TITLE
iPhone Carplay CARLINKIT issue

### ISSUE THREAD

**Issue by nukm4n** [xeon1989/Proton-X50-APK-Installer-ATLAS#3] opened 2023-02-14 05:40 UTC
Need to install package update in LINKIT app everytime IHU start up.

Workaround:
1. Disconnect Carlinkit from IHU USB
2. Open LINKIT app, go to settings, scroll down until Update
3. Install update, will need to download package everytime.
4. The prompt will say installation failed, click Done
5. Connect Carlinkit device into IHU USB
6. Start LINKIT app again, now able to connect with iPhone for Carplay

Please look into this issue.

Thank You

**Comment by xeon1989** [comment] 2023-02-14 11:16
Hi, the ordinary way to install app would not works in ATLAS, thus update failed.
As Android user myself, I can't test the scenario.
Do you get any options to skip the update or disable update check?

**Comment by nghaosiong98** [comment] 2023-02-15 02:05
I think I hit the same issue on my GKUI last time. The app is stuck at "Please insert device" forever. The connection to the LINKIT's Bluetooth and wifi keep disconnecting. After that, I saw someone in the X50 community FB group suggest installing the older version of the app. I tried installing version 2021 and it works fantastically. Hopefully, this can help in your case.

**Comment by nukm4n** [comment] 2023-02-15 02:10
How do I install version 2021 if I cannot sideload app on Atlas X50?

**Comment by xeon1989** [comment] 2023-02-15 03:03
Hi, i have confirmed with a few others who utilized the script and installed autokit, no issue even without restart.
I suspect it might be due to issue with installation.
Could you please share the log file in this issue?
It's in the root of your USB drive with file name "outputInstall_xxx.txt".

**Comment by Khangf** [comment] 2023-02-15 05:30
I am facing the similar issue as @nukm4n but mine is worse. I could never start my carplay with CARLINKIT, it just always stuck in "Please insert device" stage. I had this issue previously even in GKUI after I updated my carplay dongle through the app, not sure whether is that the reason why it broke the dongle.

> Hi, i have confirmed with a few others who utilized the script and installed autokit, no issue even without updates. I suspect it might be due to issue with installation. Could you please share the log file in this issue? It's in the root of your USB drive with file name "outputInstall_xxx.txt".

Could you ask/share which model of the dongle that they are using that are working properly?
According to the logs, it looks okay except unable to start one of the Intent where I don't think should be the issue.
[outputInstall_1676425797.txt](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/files/10739597/outputInstall_1676425797.txt)

**Comment by xeon1989** [comment] 2023-02-15 07:04
> I am facing the similar issue as @nukm4n but mine is worse. I could never start my carplay with CARLINKIT, it just always stuck in "Please insert device" stage. I had this issue previously even in GKUI after I updated my carplay dongle through the app, not sure whether is that the reason why it broke the dongle.
> 
> > Hi, i have confirmed with a few others who utilized the script and installed autokit, no issue even without updates. I suspect it might be due to issue with installation. Could you please share the log file in this issue? It's in the root of your USB drive with file name "outputInstall_xxx.txt".
> 
> Could you ask/share which model of the dongle that they are using that are working properly? According to the logs, it looks okay except unable to start one of the Intent where I don't think should be the issue. [outputInstall_1676425797.txt](https://github.com/xeon1989/Proton-X50-APK-Installer-ATLAS/files/10739597/outputInstall_1676425797.txt)
> 
> Update: There's three type of carkit dongle, CCPM(WIRED), CCPW & CCPA (WIRELESS). [Carlinkit.com](https://www.carlinkit.com/Aftermarket) What I have is CCPW, which is the one not working currently. Just ordered CCPA dongle, will update whether it works or not once I receive it.

Unlike nukm4n, your issue seems to be relevant to carlinkit device.
Please let me know if CCPA behave differently.

**Comment by sunspiider** [comment] 2023-02-15 07:54
Notes - I'm not using Xeon script.

Hi, just my input. 2 issues when sideload apk version ending with AutoKit_2022.06.27.1555.apk in AtlasOS

When plug AutoKit wired or wireless (I own both), the the installed APK will ask the box to be upgraded. AtlasOS able to upgrade the box firmware. Then when the box has higher firmware... the box wants AutoKit_2022.06.27.1555.apk to be upgraded AutoKit_2022.08.18.1707.apk.

This is where the behavior seen as, when trying to update ... ArlasOs said it failed... but the autokit now magically working. 

Then when the head unit powered down... and back up... the autokit will not work and the ""failure"" update steps have to be performed again.

This AutoKit_2022.08.18.1707.apk is not easy to find. 

1. Have to get by staging a download from another HU that allow the file to be copied out. tested working. 
2. Download from XDA site with the recent post this year. tested working also.

And I cannot test using Xeon script because when I try to change something. the script won't run, or I bad at copy pasting or I sucks at it.

**Comment by sunspiider** [comment] 2023-02-16 12:32
Disclaimer:
X50 Flagship
Hardware 300
AtlasOS latest

Execuse the typos and English. 

Try this

Run the ATLAS_617_618_uninstall script. Reason being the script does not allow to uninstall an app... so have to nuke everything.

Then replace this file ATLAS_617_618_install\app\hutroops.cn.manstep.phonemirrorBox\cn.manstep.phonemirrorBox.apk with official apk - https://www.carlinkit.com/download.html My case - Applicable products：CCPM、CCPW、CCPA - AutoKit_2022.11.15.1535.apk

For compatibility of the future script... rename the AutoKit_2022.11.15.1535.apk to cn.manstep.phonemirrorBox.apk

Then run back the ATLAS_617_618_install script.

![Capture](https://user-images.githubusercontent.com/125438852/219363353-eb5788f5-82e1-4456-96f9-4dff36bab278.PNG)

Issue -

Only 1 detected. During carplay... if you switch back to head unit app... let say you wanna see you car milage. then switch back to Carlink kit app.... the display will freeze. Audio will work... could be my box issue...  maybe cap ayam

Futher checking. 
For wireless Carlink kit... somehow... the Bluetooth failed to reconnect back when the app is in suspend mode.... work around... is to unplug the device and plug back... so it kind of defeat the user experience. Some more the box is way down.

My workaround
In my case I use my wired box... when I accidently have this freeze issue, I just unplug the lightning cable and plug back...

Other observation
My other car fitted with factory CarPlay sometime... rarely have this frezze issue. So I do same thing... I just unplug the cable and plug back. All good. maybe may factory fitted carplay also cap ayam.


![Capture2](https://user-images.githubusercontent.com/125438852/219365822-7002f744-be71-4dcb-9c99-997c525183c8.PNG)

**Comment by jctang1028** [comment] 2023-02-16 17:32
For my side, there are two issues when use Apple CarPlay
1. Wheel buttons next/previous button not working
2. When exit the autokit and enter again the app will freeze, and failed to connect the dongle Bluetooth, need unplug and plug again  to back to normal

btw I’m using ccpa dongle.

**Comment by sunspiider** [comment] 2023-02-18 03:22
> For my side, there are two issues when use Apple CarPlay
> 
> 1. Wheel buttons next/previous button not working
> 2. When exit the autokit and enter again the app will freeze, and failed to connect the dongle Bluetooth, need unplug and plug again  to back to normal
> 
> btw I’m using ccpa dongle.

---

Could you go to:

Setting... left top screen.
Click  "**Hardware**" words right top screen.
Perform the auto detection.
Then back to previous menu.. then
- Change to highest resolution available
- Change to 60fps  - For fun.. Why not

Then go to Advance setting.
Change the render from Other to Default
Then set Autoplay Music to "No"  

Now test it out.

For music... use the HU build music... like Joox... Syok... Normal radio... and try to "next" & "Previous" using steering button

See if it still freeze. When you rever or give signal..

Regards

Notes* _Can always reset to factory setting in the Advance menu.. way down before the check update button_

**Comment by jctang1028** [comment] 2023-02-18 16:54
> > For my side, there are two issues when use Apple CarPlay
> > 
> > 1. Wheel buttons next/previous button not working
> > 2. When exit the autokit and enter again the app will freeze, and failed to connect the dongle Bluetooth, need unplug and plug again  to back to normal
> > 
> > btw I’m using ccpa dongle.
> 
> For issue no. 2
> 
> Disconnect the phone first.
> 
> Could you go to:
> 
> Setting... left top screen. Click "**Hardware**" words right top screen. Perform the auto detection. Then back to previous menu.. then
> 
> * Change to highest resolution available
> * Change to 60fps  - For fun.. Why not
> 
> Then go to Advance setting. Change the **render** from Other to **Default** Then set Autoplay Music to "No"
> 
> Now test it out.
> 
> For music... use the HU build music... like Joox... Syok... Normal radio... and try to "next" & "Previous" using steering button
> 
> See if it still freeze. When you reverse or give signal..
> 
> Regards
> 
> Notes* _Can always reset to factory setting in the Advance menu.. way down before the check update button_

It’s work but the CarPlay will become a bit laggy when change the render mode to default

**Comment by sunspiider** [comment] 2023-02-19 14:47
> > > For my side, there are two issues when use Apple CarPlay
> > > 
> > > 1. Wheel buttons next/previous button not working
> > > 2. When exit the autokit and enter again the app will freeze, and failed to connect the dongle Bluetooth, need unplug and plug again  to back to normal
> > > 
> > > btw I’m using ccpa dongle.
> > 
> > 
> > For issue no. 2
> > Disconnect the phone first.
> > Could you go to:
> > Setting... left top screen. Click "**Hardware**" words right top screen. Perform the auto detection. Then back to previous menu.. then
> > 
> > * Change to highest resolution available
> > * Change to 60fps  - For fun.. Why not
> > 
> > Then go to Advance setting. Change the **render** from Other to **Default** Then set Autoplay Music to "No"
> > Now test it out.
> > For music... use the HU build music... like Joox... Syok... Normal radio... and try to "next" & "Previous" using steering button
> > See if it still freeze. When you reverse or give signal..
> > Regards
> > Notes* _Can always reset to factory setting in the Advance menu.. way down before the check update button_
> 
> It’s work but the CarPlay will become a bit laggy when change the render mode to default

Maybe lower back the FPS to 25. If that help.

Nothing much can be done after that. 

Now, focusing on seeing if possible, to get the stereng button works. Heard someone on GKUI has it work... Need the Autokit version to see the diff. 

But not going to spend much time as I'm coming from Gen2 **without** stereng button to x50... and not able to use stereng button... so no big diff for me.

**Comment by jctang1028** [comment] 2023-02-19 16:40
I found a prefect way (not prefect but at least can work smoothly) to solve two issues that I said, thank you @sunspiider for sharing cuz I follow his solution plus one more setting so the CarPlay won’t freezing and also able to use wheel steering button to next/previous song

Go to setting on left top screen (don’t connect CarPlay first)
1. FPS change to 25

then go to advance setting
2. Render mode change to “default“
3. Audio channel change to “Bluetooth”
4. Auto play music change to “Off”

Then make sure your iPhone connect to ihu Bluetooth so you can use wheel steering button during use Apple CarPlay and Apple CarPlay won’t freezing even u leave the app and enter again

**Comment by xeon1989** [comment] 2023-02-19 16:48
@jctang1028 I have put up the workaround for steering button in [this docs](SteeringButtonWorkaroundAA.md).
README updated too. 
As long as mobile phone connected via BT, track switching should not be an issue with the workaround. 

Since BT only used for track switching, I think audio channel not neccessary needed to change to Bluetooth? 
Feel free to try as I am not able to verify this behaviour. :(

**Comment by jctang1028** [comment] 2023-02-19 17:13
> @jctang1028 I have put up the workaround for steering button in [this docs](SteeringButtonWorkaroundAA.md). README updated too. As long as mobile phone connected via BT, track switching should not be an issue with the workaround.
> 
> Since BT only used for track switching, I think audio channel not neccessary needed to change to Bluetooth? Feel free to try as I am not able to verify this behaviour. :(

I tried to change the audio channel to “box” but the steering button won’t , but when I switched to Bluetooth it’s  work for steering button

**Comment by xeon1989** [comment] 2023-02-19 17:16
> 

Good to know. I will include these info as remark. Thanks for the heads up!

**Comment by jctang1028** [comment] 2023-02-19 17:22
> Good to know. I will include these info as remark. Thanks for the heads up!

Welcome bro. And the fps, render mode and autoplay music need to remark too cuz the default setting is different

**Comment by xeon1989** [comment] 2023-02-19 17:45
@jctang1028 if I understand your statement correctly, those are the settings to avoid Autokit freeze up after switch between apps.
I am also creating another page to summarize "Recommended Settings", if my assumption were true, I believe those can be added in said page. 🤔

**Comment by jctang1028** [comment] 2023-02-19 18:01
> @jctang1028 if I understand your statement correctly, those are the settings to avoid Autokit freeze up after switch between apps.
> I am also creating another page to summarize "Recommended Settings", if my assumption were true, I believe those can be added in said page. 🤔

Yes
“Audio channel” and “autoplay music” setting to able use wheel steering button when switching song via bt 
“Render mode” setting to avoid app freeze when switch app
“Fps” setting so the CarPlay can run smoothly avoid laggy

**Comment by sunspiider** [comment] 2023-02-20 03:03
> > @jctang1028 if I understand your statement correctly, those are the settings to avoid Autokit freeze up after switch between apps.
> > I am also creating another page to summarize "Recommended Settings", if my assumption were true, I believe those can be added in said page. 🤔
> 
> Yes “Audio channel” and “autoplay music” setting to able use wheel steering button when switching song via bt “Render mode” setting to avoid app freeze when switch app “Fps” setting so the CarPlay can run smoothly avoid laggy

To be confrom, we are updating the steps for standard xeon APK.. not the version I use right?

Autokit 2022.06.27.1555 (xeon script) vs AutoKit_2022.11.15.1535.apk (official website)

**Comment by jctang1028** [comment] 2023-02-20 15:00
> > > @jctang1028 if I understand your statement correctly, those are the settings to avoid Autokit freeze up after switch between apps.
> > > I am also creating another page to summarize "Recommended Settings", if my assumption were true, I believe those can be added in said page. 🤔
> > 
> > 
> > Yes “Audio channel” and “autoplay music” setting to able use wheel steering button when switching song via bt “Render mode” setting to avoid app freeze when switch app “Fps” setting so the CarPlay can run smoothly avoid laggy
> 
> To be confrom, we are updating the steps for standard xeon APK.. not the version I use right?
> 
> Autokit 2022.06.27.1555 (xeon script) vs AutoKit_2022.11.15.1535.apk (official website). I assume this fix @nukm4n issue.

Since your autokit is latest version and also have freeze app issue, are you apply the same setting that u told to solve the app freeze issue? If yes I think both version of autokit also work that recommended setting

**Comment by sunspiider** [comment] 2023-02-21 00:46
> Please insert device

I had 3 issues
1. Please insert device - Forever asking - Fixed by using Autokit latest
2. Freeze issue - Fixed by choosing diff render
3. Stereng buttons - Will try your workaround on the latest autokit soon.  Will test wired and wireless.

**Comment by Khangf** [comment] 2023-02-24 10:54
Update:
Got my CCPA dongle few days ago but no chance of driving long distance. All looks good for short drive, connect flawlessly everytime.

**Comment by xeon1989** [comment] 2023-02-24 12:24
yesterday i updated installation script to have 2022.11 autokit.
Feel free to give it a try see if any issue.

**Comment by jctang1028** [comment] 2023-02-25 02:06
Both autokit version can use same recommended setting
But I suggest install autokit 2022.11 cuz the version is up to date

**Comment by vibrain-g** [comment] 2023-02-25 13:20
Issue no 2 Same thing happen to me. Need to unplugged dongle and plug in
again.

**Comment by xeon1989** [comment] 2023-02-25 23:38
> Issue no 2 Same thing happen to me. Need to unplugged dongle and plug in again.

Have you tried this recommendation?

2. Render mode change to “default“

**Comment by jctang1028** [comment] 2023-02-26 17:59
CarPlay issue update: (after apply recommended setting and installed 2022.11 version)
1. Short drive run flawlessly 
2. Long drive (around 30minutes) CarPlay will freeze 

Remark:
1. Ccpa carlinkit dongle
2. tested in wireless , will try for wired

**Comment by sunspiider** [comment] 2023-02-27 01:44
> CarPlay issue update: (after apply recommended setting and installed 2022.11 version)
> 
> 1. Short drive run flawlessly
> 2. Long drive (around 30minutes) CarPlay will freeze
> 
> Remark:
> 
> 1. Ccpa carlinkit dongle
> 2. tested in wireless , will try for wired

Question
Are you going to test with a diff wired dongle  or the same dongle but plug wire into it .. because my wireless have cable option. 

Remarks
1. Hours drive (around 2 hours jem) seem no problem with this **CCPM** - The yellow package.
2. About every 30 mins drive with **CCPA** - The audio chocked... but never try more than 2 hours drive yet
3. For x50 FS, I lowed down the resolution to lowest as if I use higher resolution ... icon seem to be very small for my fat finger.

**Comment by jctang1028** [comment] 2023-02-27 01:56
> > CarPlay issue update: (after apply recommended setting and installed 2022.11 version)
> > 
> > 1. Short drive run flawlessly
> > 2. Long drive (around 30minutes) CarPlay will freeze
> > 
> > Remark:
> > 
> > 1. Ccpa carlinkit dongle
> > 2. tested in wireless , will try for wired
> 
> Question Are you going to test with a diff wired dongle or the same dongle but plug wire into it .. because my wireless have cable option.
> 
> Remarks
> 
> 1. Hours drive (around 2 hours jem) seem no problem with this **CCPM** - The yellow package.
> 2. About every 30 mins drive with **CCPA** - The audio chocked... but never try more than 2 hours drive yet
> 3. For x50 FS, I lowed down the resolution to lowest as if I use higher resolution ... icon seem to be very small for my fat finger.

Will use same dongle, **CCPA** can wireless and wired

**Comment by alvin5027** [comment] 2023-02-27 13:27
AutoKit - "“App not installed”" issue after update 
I accidentally click on Update for my AutoKit apps in the settings and now it show the "App not installed" when click on the app.
Do I need to use the script to uninstall all the apps and install it back ?

**Closed** 2023-03-17 01:24 UTC
